In [1]:
import pandas as pd

In [2]:
Dataset = pd.read_csv(
    "UK_Sanctions_Reduced.csv",
)
print(Dataset.head())

print(Dataset.shape)
print(Dataset.columns.tolist())

  Unique ID                                        Name Date of Birth  \
0   AFG0001  HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE       Unknown
1   AFG0001                            Haji Alim Hawala       Unknown
2   AFG0001                           Haji Hakim Hawala       Unknown
3   AFG0001              Haji Khair Ullah Money Service       Unknown
4   AFG0001              Haji Khairullah Money Exchange       Unknown

    Gender     Name Type Designation Source Designation Type Last Updated  \
0  Unknown  Primary Name                 UN           Entity   16/04/2026
1  Unknown         Alias                 UN           Entity   16/04/2026
2  Unknown         Alias                 UN           Entity   16/04/2026
3  Unknown         Alias                 UN           Entity   16/04/2026
4  Unknown         Alias                 UN           Entity   16/04/2026

                           Address Country Birth Country Nationalities  \
0  Afghanistan, Iran, United Arab Emirates       Unknown       Unknown
1  Afghanistan, Iran, United Arab Emirates       Unknown       Unknown
2  Afghanistan, Iran, United Arab Emirates       Unknown       Unknown
3  Afghanistan, Iran, United Arab Emirates       Unknown       Unknown
4  Afghanistan, Iran, United Arab Emirates       Unknown       Unknown

  National Identifier number Passport Number Sanctions Imposed  \
0                    Unknown         Unknown      Asset freeze
1                    Unknown         Unknown      Asset freeze
2                    Unknown         Unknown      Asset freeze
3                    Unknown         Unknown      Asset freeze
4                    Unknown         Unknown      Asset freeze

                                   Other Information  Address Variations
0  Afghan Money Service Provider License Number: ...                  16
1  Afghan Money Service Provider License Number: ...                  16
2  Afghan Money Service Provider License Number: ...                  16
3  Afghan Money Service Provider License Number: ...                  16
4  Afghan Money Service Provider License Number: ...                  16
(17102, 16)
['Unique ID', 'Name', 'Date of Birth', 'Gender', 'Name Type', 'Designation Source', 'Designation Type', 'Last Updated', 'Address Country', 'Birth Country', 'Nationalities', 'National Identifier number', 'Passport Number', 'Sanctions Imposed', 'Other Information', 'Address Variations']

In [3]:
Dataset.sample(n=20, random_state=42)

,Unique ID,Name,Date of Birth,Gender,Name Type,Designation Source,Designation Type,Last Updated,Address Country,Birth Country,Nationalities,National Identifier number,Passport Number,Sanctions Imposed,Other Information,Address Variations
10043,RUS0229,Alexander Victorovych Janukovych,10/07/1973,Male,Primary Name Variation,UK,Individual,09/04/2025,Russia,Former USSR Currently Ukraine,Ukraine,Unknown,Unknown,Asset freeze|Travel Ban|Trust Services Sanctio...,The Director Disqualification Sanction was imp...,1
6679,GHR0051,Viktor Aliaksandravich LUKASHENKO,28/11/1975,Male,Primary name,UK,Individual,09/04/2025,Belarus,Belarus,Belarus,Unknown,Unknown,Asset freeze|Travel Ban|Director Disqualificat...,The Director Disqualification Sanction was imp...,1
7585,INU0112,National University of Iran,Unknown,Unknown,Alias,UK,Entity,09/04/2025,Iran,Unknown,Unknown,Unknown,Unknown,Asset freeze|Director Disqualification Sanction,The Director Disqualification Sanction was imp...,2
8846,IRN0232,Mohammad-Hossein Dadras,Unknown,Male,Primary Name Variation,UK,Individual,09/04/2025,Iran,Iran,Iran,Unknown,Unknown,Asset freeze|Travel Ban|Director Disqualificat...,The Director Disqualification Sanction was imp...,1
7640,INU0127,TEM,Unknown,Unknown,Alias,UK,Entity,09/04/2025,Iran,Unknown,Unknown,Unknown,Unknown,Asset freeze|Director Disqualification Sanction,The Director Disqualification Sanction was imp...,1
14740,SOM0012,Abubaker Shariff,1967,Unknown,Alias,UN,Individual,18/12/2021,Kenya,Kenya,Unknown,Unknown,Unknown,Asset freeze|Travel Ban,Unknown,1
15391,SYR0065,Abdallah Khalil Hussain,1959,Male,Primary name variation,UK,Individual,01/05/2025,Unknown,Unknown,Unknown,Unknown,Unknown,Asset freeze|Travel Ban|Director Disqualificat...,The Director Disqualification Sanction was imp...,1
13095,RUS2428,TKT-1997 RAZVOJ LIMITED,Unknown,Unknown,Primary Name,UK,Entity,09/04/2025,China,Unknown,Unknown,Unknown,Unknown,Asset freeze|Trust Services Sanctions|Director...,The Director Disqualification Sanction was imp...,1
2998,AQD0292,Abu Ubaydah,16/09/1973,Unknown,Alias,UN,Individual,18/12/2021,Unknown,"Sudan, Yemen","Sudan, Yemen",Unknown,'00085243,Asset freeze|Arms embargo|Travel Ban,"Arrested in Karachi, Pakistan, 30 Sep. 2002. I...",1
6698,GHR0053,Khazalbek Bakhtibekavich Atabekau,Unknown,Male,Primary name variation,UK,Individual,09/04/2025,Belarus,Unknown,Belarus,Unknown,Unknown,Asset freeze|Travel Ban|Director Disqualificat...,The Director Disqualification Sanction was imp...,1
14447,RUS3417,LLC PALFINGER SANI CRANES,Unknown,Unknown,Primary Name,UK,Entity,24/02/2026,Russia,Unknown,Unknown,Unknown,Unknown,Asset freeze|Trust Services Sanctions|Director...,Unknown,1
14247,RUS3273,UNITYCOMEX TRADING LIMITED FZE,Unknown,Unknown,Primary Name,UK,Entity,24/02/2026,United Arab Emirates,Unknown,Unknown,Unknown,Unknown,Asset freeze|Trust Services Sanctions|Director...,Transport sanctions: where transport sanctions...,1
7717,INU0230,FAATER INSTITUTE,Unknown,Unknown,Primary name variation,UK|UN,Entity,01/10/2025,Unknown,Unknown,Unknown,Unknown,Unknown,Asset freeze|Director Disqualification Sanction,FATER INSTITUTE was listed pursuant to paragra...,1
4413,CAF0010,JOSEPH KONY,1959,Unknown,Primary name,UN,Individual,18/12/2021,"Central African Republic, Congo (Democratic Re...",Uganda,Unknown,Unknown,Unknown,Asset freeze|Travel Ban,Kony is the founder and leader of the Lord’s R...,8
12331,RUS1918,Aleksei Gennadievich KOMISSAROV,20/10/1969,Male,Primary Name,UK,Individual,09/04/2025,Unknown,Russia,Unknown,Unknown,Unknown,Asset freeze|Travel Ban|Trust Services Sanctio...,The Director Disqualification Sanction was imp...,1
5763,DPR0203,Jo Yon Jun,28/09/1937,Unknown,Alias,UN,Individual,01/08/2022,Unknown,Unknown,Unknown,Unknown,Unknown,Asset freeze|Chartering of Ships|Prevention of...,Unknown,1
9373,MYA0082,Royal Shune Lei,Unknown,Unknown,Alias,UK,Entity,09/04/2025,Myanmar,Unknown,Unknown,Unknown,Unknown,Asset freeze|Director Disqualification Sanction,The Director Disqualification Sanction was imp...,1
6405,GAC0017,Atul Kumar GUPTA,14/06/1968,Male,Primary name,UK,Individual,09/04/2025,United Arab Emirates,India,"India, South Africa",Unknown,233646059,Asset freeze|Travel Ban|Director Disqualificat...,Associated with: Ajay Kumar Gupta (brother/bus...,1
12441,RUS1980,PARAMOUNT ENERGY & COMMODITIES DMCC,Unknown,Unknown,Primary Name,UK,Entity,14/04/2025,United Arab Emirates,Unknown,Unknown,Unknown,Unknown,Asset freeze|Trust Services Sanctions|Director...,Transport sanctions: where transport sanctions...,1
5843,DPR0239,Kim Hyok-Chol,1964,Unknown,Alias,UN,Individual,01/08/2022,Unknown,Unknown,North Korea,Unknown,290320764,Asset freeze|Chartering of Ships|Prevention of...,Kim Tong My’ong is the President of Tanchon Co...,1

In [4]:
#Test - Filtering by Unique ID (Exact)
Dataset[Dataset["Unique ID"] == "AFG0001"]

,Unique ID,Name,Date of Birth,Gender,Name Type,Designation Source,Designation Type,Last Updated,Address Country,Birth Country,Nationalities,National Identifier number,Passport Number,Sanctions Imposed,Other Information,Address Variations
0,AFG0001,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,Unknown,Unknown,Primary Name,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16
1,AFG0001,Haji Alim Hawala,Unknown,Unknown,Alias,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16
2,AFG0001,Haji Hakim Hawala,Unknown,Unknown,Alias,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16
3,AFG0001,Haji Khair Ullah Money Service,Unknown,Unknown,Alias,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16
4,AFG0001,Haji Khairullah Money Exchange,Unknown,Unknown,Alias,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16
5,AFG0001,Haji Khairullah and Abdul Sattar and Company,Unknown,Unknown,Alias,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16
6,AFG0001,Haji Khairullah-Haji Sattar Sarafi,Unknown,Unknown,Alias,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16
7,AFG0001,Haji Salam Hawala,Unknown,Unknown,Alias,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16
8,AFG0001,Sarafi-yi Haji Khairullah Haji Satar Haji Esma...,Unknown,Unknown,Alias,UN,Entity,16/04/2026,"Afghanistan, Iran, United Arab Emirates",Unknown,Unknown,Unknown,Unknown,Asset freeze,Afghan Money Service Provider License Number: ...,16

In [5]:
#Test - Filtering by Date of Birth (Contains)
Dataset[Dataset["Date of Birth"].str.contains("03/1969", na=False)]

,Unique ID,Name,Date of Birth,Gender,Name Type,Designation Source,Designation Type,Last Updated,Address Country,Birth Country,Nationalities,National Identifier number,Passport Number,Sanctions Imposed,Other Information,Address Variations
11007,RUS1005,Grigory Petrovich LEDKOV,26/03/1969,Unknown,Primary Name,UK,Individual,09/04/2025,Russia,Russia,Unknown,Unknown,Unknown,Asset freeze|Travel Ban|Trust Services Sanctio...,The Director Disqualification Sanction was imp...,1
11797,RUS1538,Vladislav Garievich KUZNETSOV,18/03/1969,Male,Primary Name,UK,Individual,09/04/2025,Unknown,Russia,Russia,Unknown,Unknown,Asset freeze|Travel Ban|Trust Services Sanctio...,The Director Disqualification Sanction was imp...,1
11980,RUS1668,Denis Valentinovich MANTUROV,23/03/1969,Male,Primary Name,UK,Individual,09/04/2025,Russia,Russia,Russia,Unknown,511787479,Asset freeze|Travel Ban|Trust Services Sanctio...,The Director Disqualification Sanction was imp...,1
17018,VEN0030,Juan Jose Mendoza Jover,11/03/1969,Male,Primary name,UK,Individual,09/04/2025,Venezuela,Venezuela,Venezuela,V-9499372,Unknown,Asset freeze|Travel Ban|Director Disqualificat...,The Director Disqualification Sanction was imp...,1

In [6]:
#Test - Filtering by Nationalities (Contains)
Dataset[Dataset["Nationalities"].str.contains("Canada", na=False)]

,Unique ID,Name,Date of Birth,Gender,Name Type,Designation Source,Designation Type,Last Updated,Address Country,Birth Country,Nationalities,National Identifier number,Passport Number,Sanctions Imposed,Other Information,Address Variations
4792,CTI0007,El-Hajj,22/03/1988,Male,Alias,UK,Individual,09/04/2025,Lebanon,Unknown,Canada,Unknown,JX446643,Asset freeze|Arms embargo|Travel Ban|Director ...,The Director Disqualification Sanction was imp...,1
4793,CTI0007,El-Hajj Hassan,22/03/1988,Male,Alias,UK,Individual,09/04/2025,Lebanon,Unknown,Canada,Unknown,JX446643,Asset freeze|Arms embargo|Travel Ban|Director ...,The Director Disqualification Sanction was imp...,1
4794,CTI0007,Hassan El-Hajj,22/03/1988,Male,Primary name,UK,Individual,09/04/2025,Lebanon,Unknown,Canada,Unknown,JX446643,Asset freeze|Arms embargo|Travel Ban|Director ...,The Director Disqualification Sanction was imp...,1
11521,RUS1338,Eugene Tenenbaum,09/1964,Male,Primary Name,UK,Individual,28/07/2023,Unknown,Ukraine,Canada,Unknown,Unknown,Asset freeze|Trust Services Sanctions|Transpor...,Transport sanction: where transport sanctions ...,1
14116,RUS3165,Murtaza Ali LAKHANI,08/03/1962,Male,Primary Name,UK,Individual,18/12/2025,United Kingdom,Pakistan,"Canada, Pakistan",Unknown,Unknown,Asset freeze|Travel Ban|Trust Services Sanctio...,"Transport sanctions: ships owned, controlled, ...",1